### ISSUE TITLE
Serious Bug: Map - Mobile map doesn’t update when viewing an organization

### ISSUE THREAD

**Issue by fancyham** [hackforla/food-oasis#2028]
#### Describe the bug 

Serious bug:

When viewing a list of organizations, and tapping one to get details about it, the map does not update show or highlight the organization’s pin.  Often the pin is way off-screen.

The map should re-center (ideally with a smooth scroll/pan) on the highlighted pin automatically, ideally showing both the user’s current location and the pin so that they can determine the relative location.

#### Steps to reproduce the issue

(if applicable, please specify platform (iOS, Android, Windows, Mac version) and brower)

1. Go to foodoasis.net
2. Enter a location to get a list of organizations
3. Scroll around the map, zoom in, zoom out
4. Tap an organization to view the organization detail page
5. Map does not update to show the organization’s pin.

#### What's the expected result?

Map should re-center on the organization’s pin automatically, each time a new organization is viewed.  

Ideally, the map smoothly pans to the new location, and ideally, the user’s current location / entered address is also visible on the map (though this may be difficult if the user has panned the map manually)

See Apple or Google maps or Yelp on mobile phones for example.

#### What's the actual result?

The organization’s pin may be highlighted, but is often off-screen with no indication for how to find the pin itself.

This is a regression — the previous version centered on highlighted pins properly.

#### Additional details / screenshot

A similar problem appears when searching from the map screen. 
1. From landing page, enter an address. On desktop, map Pin appears in the wrong place but map pans correct place at first.
![IMG_1253](https://github.com/user-attachments/assets/cf8cc736-3d32-4d47-b1df-c11b90211b6e)

2. Do a search again from the map page and the map now re-centers in the wrong place, and the pin doesn’t move to the correct place. 
![IMG_1252](https://github.com/user-attachments/assets/8f2c2963-54e4-4f92-8cde-400a22217782)

https://github.com/user-attachments/assets/4ee431c6-d986-4282-9694-7ef13badf7d1

To it might have something to do with loading the page for the first time vs going to a new location

#### Device configuration
- Device: iPhone 13 mini
- OS version: 17.4
- Browser: Safari

### Related issues

- #2168

**Comment by fancyham** [comment]
Hi @hanapotski , just checked out the devla site today and there's something weird happening:

When I tap on an org pin, the pin smooth-scrolls off the screen!  Very smooth, but kinda weird :)

https://github.com/hackforla/food-oasis/assets/3376957/b0198e69-a47f-4c6e-a896-7d58698ad55b

**Comment by hanapotski** [comment]
Thanks 🙏 This is a known bug. Qiqi's looking into it 👌

**Comment by danvgar** [comment]
Still working on this, but adding notes here for future me and future team:

 - I suspect related to 
  - #2065
  - #2110 
 - Issue seems to reproduce _after_ adjusting map scale (aka zooming in/out). Locations are centered at first, but changing scale adds offsets to lat-long coordinates each time. Similar for clicking locations from side panel vs from map itself 
 
![Jun-30-2024 10-29-35](https://github.com/hackforla/food-oasis/assets/124107401/3b74fde9-02cd-47fb-8864-87a6399c880f)

**Comment by danvgar** [comment]
I believe issue is at [L119](https://github.com/hackforla/food-oasis/blob/df35240ad3ac35929f2ba749fb91654b94d1820d/client/src/components/FoodSeeker/SearchResults/ResultsMap/ResultsMap.js#L116) of `ResultsMap.js` and [L96](https://github.com/hackforla/food-oasis/blob/df35240ad3ac35929f2ba749fb91654b94d1820d/client/src/components/FoodSeeker/SearchResults/layouts/Desktop.js#L96 of `Desktop.js`

In `Desktop.js`, the width of the Mapbox viewport is always 100% of the device width. Opening or closing the List Panel does not affect this, as the List Panel is in the z-index above the Mapbox viewport. 

In `ResultsMap.js`, the `center` is offset by a constant lat/long value based on whether the List Panel is open. However, these constants are only accurate for the default zoom, and won't be entirely accurate if the zoom level is changed. 

<img width="1661" alt="Screenshot 2024-06-30 at 12 10 24 PM" src="https://github.com/hackforla/food-oasis/assets/124107401/14f16eff-f736-4de3-850a-35dcf15c0936">
<img width="1662" alt="Screenshot 2024-06-30 at 12 10 09 PM" src="https://github.com/hackforla/food-oasis/assets/124107401/f2f01a57-3d1e-40ed-b347-87f06d87ead7">

Two potential solutions:
1. Adjust the `Desktop.js` layout so that the mapbox width is adjusted when the List Panel is open, and remove the long/lat offsets. 
2. Change the offsets from a constant to a linear equation, so that the offsets adjust based on the zoom level. This would take some experimenting or research to figure out the exact equation. (e.g. lat = lat - 0.08 * zoom / 11)

**Comment by fancyham** [comment]
The same issue appears on mobile - and it’s trickier since the map viewport can change when the text panel resizes:
- #2168 

the above issue is very serious as it makes the mobile site very unusable

**Comment by hanapotski** [comment]
closing this as this was fixed in [this PR](https://github.com/hackforla/food-oasis/pull/2174)

**Comment by fancyham** [comment]
Hi -- I just QAed at devla.foodoasis.net -- could you check on these two issues?  (I'm reopening this so it grabs your attention but let me know if there's something else we should do for QA stuff)

* On screens 500-800px wide, the map pin isn't centered properly -- it's off to the right
* On mobile screens, the pin still gets cut off?  Seems like it's not recalculating the visible map size, but is expecting the text panel to be at 50% -- but that's not always the case and I think the org details appear at about ~75% of the screen, so map pin is obscured.

Uploading Screen Recording 2024-08-05 at 7.22.20 PM 720p.mov…

**Comment by hanapotski** [comment]
Not sure if it's a normal behavior for a user to resize the window 🤔

**Comment by fancyham** [comment]
It doesn’t require resizing - that’s just to show the issues at different sizes, and the working one at desktop size. Try it out with browsers at those sizes - iPad portrait and a smartphone

**Comment by Shienny1** [comment]
Hi Guys. I checked the devla.foodoasis.net site : this is what I am experiencing still: The icons are nonresponsive at times. And they are still NOT CENTERED in the selected location in the mobile version. Please see the clip attached:

https://github.com/user-attachments/assets/19cab516-3373-4a95-aaae-baaea8af4b04

**Comment by fancyham** [comment]
This issue seems like a subset of 
- #2168 

Please look at both — it’s likely the solution fixes both bugs.  

This is high priority because the site is very unusable and buggy when the map goes off in unexpected directions!  Hot-fix asap, please!

**Comment by hanapotski** [comment]
Hi 👋 we are aware of the unresponsive icons bug, we have a [ticket](https://github.com/hackforla/food-oasis/issues/2177) for it. Someone's already taking a look at it 👍

**Comment by hanapotski** [comment]
> Still working on this, but adding notes here for future me and future team:
> 
> * I suspect related to
>   
>   * [Serious Bug: GPS button doesn’t re-center on current location #2065](https://github.com/hackforla/food-oasis/issues/2065)
>   * [Fix flyTo on mobile #2110](https://github.com/hackforla/food-oasis/pull/2110)
> * Issue seems to reproduce _after_ adjusting map scale (aka zooming in/out). Locations are centered at first, but changing scale adds offsets to lat-long coordinates each time. Similar for clicking locations from side panel vs from map itself (Desktop)
> * Issue only shows up when side panel is open. (Desktop)
> 
> ![Jun-30-2024 10-29-35](https://private-user-images.githubusercontent.com/124107401/344483629-3b74fde9-02cd-47fb-8864-87a6399c880f.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM5NTc5MjcsIm5iZiI6MTcyMzk1NzYyNywicGF0aCI6Ii8xMjQxMDc0MDEvMzQ0NDgzNjI5LTNiNzRmZGU5LTAyY2QtNDdmYi04ODY0LTg3YTYzOTljODgwZi5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxOFQwNTA3MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hYjc5YTM2Mzk1NTkxM2I3YzIwOWE1NzJhMGE0M2U3Y2M0NWQ2NzM3YTM2NDhkMzc1NTU4M2E5NDdkYTYzMzI4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.F5xTEZfBxHWm9rLjV_NdOB9zQjg090bZV2JAMM06PDo) [ ![Jun-30-2024 10-29-35](https://private-user-images.githubusercontent.com/124107401/344483629-3b74fde9-02cd-47fb-8864-87a6399c880f.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM5NTc5MjcsIm5iZiI6MTcyMzk1NzYyNywicGF0aCI6Ii8xMjQxMDc0MDEvMzQ0NDgzNjI5LTNiNzRmZGU5LTAyY2QtNDdmYi04ODY0LTg3YTYzOTljODgwZi5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxOFQwNTA3MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hYjc5YTM2Mzk1NTkxM2I3YzIwOWE1NzJhMGE0M2U3Y2M0NWQ2NzM3YTM2NDhkMzc1NTU4M2E5NDdkYTYzMzI4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.F5xTEZfBxHWm9rLjV_NdOB9zQjg090bZV2JAMM06PDo) ](https://private-user-images.githubusercontent.com/124107401/344483629-3b74fde9-02cd-47fb-8864-87a6399c880f.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM5NTc5MjcsIm5iZiI6MTcyMzk1NzYyNywicGF0aCI6Ii8xMjQxMDc0MDEvMzQ0NDgzNjI5LTNiNzRmZGU5LTAyY2QtNDdmYi04ODY0LTg3YTYzOTljODgwZi5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxOFQwNTA3MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hYjc5YTM2Mzk1NTkxM2I3YzIwOWE1NzJhMGE0M2U3Y2M0NWQ2NzM3YTM2NDhkMzc1NTU4M2E5NDdkYTYzMzI4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.F5xTEZfBxHWm9rLjV_NdOB9zQjg090bZV2JAMM06PDo) [ ](https://private-user-images.githubusercontent.com/124107401/344483629-3b74fde9-02cd-47fb-8864-87a6399c880f.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM5NTc5MjcsIm5iZiI6MTcyMzk1NzYyNywicGF0aCI6Ii8xMjQxMDc0MDEvMzQ0NDgzNjI5LTNiNzRmZGU5LTAyY2QtNDdmYi04ODY0LTg3YTYzOTljODgwZi5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxOFQwNTA3MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hYjc5YTM2Mzk1NTkxM2I3YzIwOWE1NzJhMGE0M2U3Y2M0NWQ2NzM3YTM2NDhkMzc1NTU4M2E5NDdkYTYzMzI4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.F5xTEZfBxHWm9rLjV_NdOB9zQjg090bZV2JAMM06PDo)

just saw this. I think we should add a separate ticket for this as this needs more research/experimenting

**Comment by ExperimentsInHonesty** [comment]
When making your PR. please assign @fancyham
